INSERT INTO T_USER(ID, USERNAME, `PASSWORD`, FIRST_NAME, LAST_NAME ) VALUES (1, 'ana', 'ana123', 'Ana', 'Valcu');
INSERT INTO T_USER(ID, USERNAME, `PASSWORD`, FIRST_NAME, LAST_NAME ) VALUES (2, 'bogdan', 'bogdan123', 'Bogdan', 'Stanciu');
INSERT INTO T_SPOT(ID, SPOT_NUMBER, FLOOR) VALUES (1, 1, 0);
INSERT INTO T_ASSIGNMENT(ID, USER_ID, SPOT_ID) VALUES(1, 1, 1);